name: great_places
description: "A Great place project to work"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  location: ^8.0.1
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.13.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - .env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
